/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCd;
import Modelo.CdDAO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author JONATHAN G
 */
public class CdForm extends javax.swing.JFrame {

    CdDAO cdDao = new CdDAO();

    /**
     * Creates new form CdForm
     */
    public CdForm() {
        initComponents();
        setLocationRelativeTo(null);

        ControladorCd controladorCd = new ControladorCd(this, cdDao);
        btn_agregarCd.addActionListener(controladorCd);
        btn_modificarCd.addActionListener(controladorCd);
        btn_eliminarCd.addActionListener(controladorCd);
        btn_limpiarCd.addActionListener(controladorCd);
        tabla_cd.setModel(cdDao.selectCds());

        // METODO PARA CAPURAR LOS EVENTOS DEL MOUSE AL HACER CLICK
        this.tabla_cd.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                obtenerDatosTabla(e);
                ModificarEliminarBtn();
            }
        });
        Limpiar();
    }

    public void ModificarEliminarBtn() {

        txt_idCd.setEnabled(false);
        txt_idMaterial.setEnabled(false);
        txt_idCategoria.setEnabled(false);

        btn_agregarCd.setEnabled(false);
        btn_modificarCd.setEnabled(true);
        btn_eliminarCd.setEnabled(true);
    }

    public void Limpiar() {
        txt_idCd.setEnabled(false);
        txt_idMaterial.setEnabled(false);
        txt_idCategoria.setEnabled(true);
        txt_idCd.setText("");
        txt_idMaterial.setText("");
        txt_idCategoria.setText("");
        txt_artista.setText("");
        txt_genero.setText("");
        txt_duracion.setText("");
        txt_numCanciones.setText("");
        txt_codigo.setText("");
        txt_titulo.setText("");
        sp_unidadesDisponibles.setValue(0);

        btn_agregarCd.setEnabled(true);
        btn_modificarCd.setEnabled(false);
        btn_eliminarCd.setEnabled(false);
    }

    private void obtenerDatosTabla(MouseEvent e) {

        int filaSeleccionada = tabla_cd.getSelectedRow();

        if (filaSeleccionada > -1) {
            String id_cd = tabla_cd.getValueAt(filaSeleccionada, 0).toString();
            String id_material = tabla_cd.getValueAt(filaSeleccionada, 1).toString();
            String id_categoria = tabla_cd.getValueAt(filaSeleccionada, 2).toString();
            String artista = tabla_cd.getValueAt(filaSeleccionada, 3).toString();
            String genero = tabla_cd.getValueAt(filaSeleccionada, 4).toString();
            String duracion = tabla_cd.getValueAt(filaSeleccionada, 5).toString();
            String num_canciones = tabla_cd.getValueAt(filaSeleccionada, 6).toString();
            String codigo = tabla_cd.getValueAt(filaSeleccionada, 7).toString();
            String titulo = tabla_cd.getValueAt(filaSeleccionada, 8).toString();
            String unidadesDisponibles = tabla_cd.getValueAt(filaSeleccionada, 9).toString();

            txt_idCd.setText(id_cd);
            txt_idMaterial.setText(id_material);
            txt_idCategoria.setText(id_categoria);
            txt_artista.setText(artista);
            txt_genero.setText(genero);
            txt_duracion.setText(duracion);
            txt_numCanciones.setText(num_canciones);
            txt_codigo.setText(codigo);
            txt_titulo.setText(titulo);
            sp_unidadesDisponibles.setValue(Integer.parseInt(unidadesDisponibles));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_idCd = new javax.swing.JLabel();
        txt_idCd = new javax.swing.JTextField();
        lbl_idMaterial = new javax.swing.JLabel();
        txt_idMaterial = new javax.swing.JTextField();
        lbl_artista = new javax.swing.JLabel();
        txt_artista = new javax.swing.JTextField();
        lbl_genero = new javax.swing.JLabel();
        txt_genero = new javax.swing.JTextField();
        lbl_duracion = new javax.swing.JLabel();
        lbl_numCanciones = new javax.swing.JLabel();
        txt_numCanciones = new javax.swing.JTextField();
        lbl_idCategoria = new javax.swing.JLabel();
        txt_idCategoria = new javax.swing.JTextField();
        lbl_codigo = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        lbl_titulo = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        lbl_unidadesDisponible = new javax.swing.JLabel();
        sp_unidadesDisponibles = new javax.swing.JSpinner();
        scroll_tabla = new javax.swing.JScrollPane();
        tabla_cd = new javax.swing.JTable();
        btn_agregarCd = new javax.swing.JButton();
        btn_modificarCd = new javax.swing.JButton();
        btn_eliminarCd = new javax.swing.JButton();
        btn_limpiarCd = new javax.swing.JButton();
        txt_duracion = new javax.swing.JTextField();

        lbl_idCd.setText("ID:");

        lbl_idMaterial.setText("ID Material:");

        lbl_artista.setText("Artista:");

        lbl_genero.setText("Genero:");

        lbl_duracion.setText("Duración:");

        lbl_numCanciones.setText("Número de canciones:");

        lbl_idCategoria.setText("ID Categoria:");

        lbl_codigo.setText("Código:");

        lbl_titulo.setText("Titulo:");

        lbl_unidadesDisponible.setText("Unidades disponibles:");

        tabla_cd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll_tabla.setViewportView(tabla_cd);

        btn_agregarCd.setText("Agregar");

        btn_modificarCd.setText("Modificar");

        btn_eliminarCd.setText("Eliminar");

        btn_limpiarCd.setText("Limpiar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lbl_idCd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_idCd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addComponent(lbl_idMaterial))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_codigo)
                            .addComponent(lbl_artista))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_artista)
                            .addComponent(txt_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_genero)
                            .addComponent(lbl_titulo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_idMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(lbl_duracion))
                    .addComponent(txt_titulo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbl_unidadesDisponible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_unidadesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_idCategoria))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txt_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(lbl_numCanciones)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_idCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_numCanciones))))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_agregarCd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_modificarCd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminarCd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_limpiarCd))
                    .addComponent(scroll_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idMaterial)
                    .addComponent(txt_idMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_idCd)
                    .addComponent(txt_idCd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_idCategoria)
                    .addComponent(txt_idCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_artista)
                    .addComponent(txt_artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_genero)
                    .addComponent(txt_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_duracion)
                    .addComponent(lbl_numCanciones)
                    .addComponent(txt_numCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codigo)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_titulo)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_unidadesDisponible)
                    .addComponent(sp_unidadesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarCd)
                    .addComponent(btn_modificarCd)
                    .addComponent(btn_eliminarCd)
                    .addComponent(btn_limpiarCd))
                .addGap(18, 18, 18)
                .addComponent(scroll_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_agregarCd;
    public javax.swing.JButton btn_eliminarCd;
    public javax.swing.JButton btn_limpiarCd;
    public javax.swing.JButton btn_modificarCd;
    public javax.swing.JLabel lbl_artista;
    public javax.swing.JLabel lbl_codigo;
    public javax.swing.JLabel lbl_duracion;
    public javax.swing.JLabel lbl_genero;
    public javax.swing.JLabel lbl_idCategoria;
    public javax.swing.JLabel lbl_idCd;
    public javax.swing.JLabel lbl_idMaterial;
    public javax.swing.JLabel lbl_numCanciones;
    public javax.swing.JLabel lbl_titulo;
    public javax.swing.JLabel lbl_unidadesDisponible;
    public javax.swing.JScrollPane scroll_tabla;
    public javax.swing.JSpinner sp_unidadesDisponibles;
    public javax.swing.JTable tabla_cd;
    public javax.swing.JTextField txt_artista;
    public javax.swing.JTextField txt_codigo;
    public javax.swing.JTextField txt_duracion;
    public javax.swing.JTextField txt_genero;
    public javax.swing.JTextField txt_idCategoria;
    public javax.swing.JTextField txt_idCd;
    public javax.swing.JTextField txt_idMaterial;
    public javax.swing.JTextField txt_numCanciones;
    public javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
