/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controlador.ControladorDvd;
import Modelo.DvdDAO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author Carlos Hernandez
 */
public class DvdForm extends javax.swing.JFrame {

    DvdDAO DvdDAO = new DvdDAO();
    /**
     * Creates new form Dvdform
     */
    public DvdForm() {
          initComponents();
        setLocationRelativeTo(null);

        ControladorDvd controladorDvd = new ControladorDvd(this, DvdDAO);
        btn_agregarDvd.addActionListener(controladorDvd);
        btn_modificarDvd.addActionListener(controladorDvd);
        btn_eliminarDvd.addActionListener(controladorDvd);
        btn_limpiarDvd.addActionListener(controladorDvd);
        tabla_Dvd.setModel(DvdDAO.selectdvds());

        // METODO PARA CAPURAR LOS EVENTOS DEL MOUSE AL HACER CLICK
        this.tabla_Dvd.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                obtenerDatosTabla(e);
                ModificarEliminarBtn();
            }
        });
        
        Limpiar();
    }
    
        public void ModificarEliminarBtn() {

        txt_idDvd.setEnabled(false);
        txt_idMaterial.setEnabled(false);
        txt_idCategoria.setEnabled(false);

        btn_agregarDvd.setEnabled(false);
        btn_modificarDvd.setEnabled(true);
        btn_eliminarDvd.setEnabled(true);
    }

    public void Limpiar() {
        txt_idDvd.setEnabled(false);
        txt_idMaterial.setEnabled(false);
        txt_idCategoria.setEnabled(true);
        txt_idDvd.setText("");
        txt_idMaterial.setText("");
        txt_idCategoria.setText("");
        txt_director.setText("");
        txt_genero.setText("");
        txt_duracion.setText("");
        txt_codigo.setText("");
        txt_titulo.setText("");
        sp_unidadesDisponibles.setValue(0);

        btn_agregarDvd.setEnabled(true);
        btn_modificarDvd.setEnabled(false);
        btn_eliminarDvd.setEnabled(false);
    }
private void obtenerDatosTabla(MouseEvent e) {

        int filaSeleccionada = tabla_Dvd.getSelectedRow();

        if (filaSeleccionada > -1) {
            String id_dvd = tabla_Dvd.getValueAt(filaSeleccionada, 0).toString();
            String id_material = tabla_Dvd.getValueAt(filaSeleccionada, 1).toString();
            String id_categoria = tabla_Dvd.getValueAt(filaSeleccionada, 2).toString();
            String director = tabla_Dvd.getValueAt(filaSeleccionada, 3).toString();
            String duracion = tabla_Dvd.getValueAt(filaSeleccionada, 4).toString();
            String genero = tabla_Dvd.getValueAt(filaSeleccionada, 5).toString();
            String codigo = tabla_Dvd.getValueAt(filaSeleccionada, 6).toString();
            String titulo = tabla_Dvd.getValueAt(filaSeleccionada, 7).toString();
            String unidadesDisponibles = tabla_Dvd.getValueAt(filaSeleccionada, 8).toString();

            txt_idDvd.setText(id_dvd);
            txt_idMaterial.setText(id_material);
            txt_idCategoria.setText(id_categoria);
            txt_director.setText(director);
            txt_genero.setText(genero);
            txt_duracion.setText(duracion);
            txt_codigo.setText(codigo);
            txt_titulo.setText(titulo);
            sp_unidadesDisponibles.setValue(Integer.parseInt(unidadesDisponibles));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_director = new javax.swing.JTextField();
        txt_duracion = new javax.swing.JTextField();
        txt_genero = new javax.swing.JTextField();
        lbl_codigo = new javax.swing.JLabel();
        lbl_idDvd = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        txt_idDvd = new javax.swing.JTextField();
        lbl_unidadesdisponibles = new javax.swing.JLabel();
        lbl_material = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_idMaterial = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JTextField();
        lbl_Director = new javax.swing.JLabel();
        sp_unidadesDisponibles = new javax.swing.JSpinner();
        lbl_Duracion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Dvd = new javax.swing.JTable();
        lbl_genero = new javax.swing.JLabel();
        btn_agregarDvd = new javax.swing.JButton();
        btn_modificarDvd = new javax.swing.JButton();
        btn_eliminarDvd = new javax.swing.JButton();
        btn_limpiarDvd = new javax.swing.JButton();
        lbl_categoria = new javax.swing.JLabel();
        txt_idCategoria = new javax.swing.JTextField();

        lbl_codigo.setText("Codigo:");

        lbl_idDvd.setText("ID:");

        lbl_titulo.setText("Titulo:");

        txt_idDvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idDvdActionPerformed(evt);
            }
        });

        lbl_unidadesdisponibles.setText("Unidades Disponibles:");

        lbl_material.setText("ID Meterial");

        txt_idMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idMaterialActionPerformed(evt);
            }
        });

        txt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tituloActionPerformed(evt);
            }
        });

        lbl_Director.setText("Director ");

        lbl_Duracion.setText("Duracion ");

        tabla_Dvd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_Dvd);

        lbl_genero.setText("Genero");

        btn_agregarDvd.setText("Agregar");
        btn_agregarDvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarDvdActionPerformed(evt);
            }
        });

        btn_modificarDvd.setText("Modificar ");

        btn_eliminarDvd.setText("Eliminar");

        btn_limpiarDvd.setText("Limpiar");

        lbl_categoria.setText("ID Categoria");

        txt_idCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_codigo)
                            .addComponent(lbl_Director))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lbl_idDvd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_idDvd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_material))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_director, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_titulo)
                                            .addComponent(lbl_Duracion))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(txt_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txt_idMaterial))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_genero)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_categoria)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_idCategoria))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_unidadesdisponibles)
                                        .addGap(18, 18, 18)
                                        .addComponent(sp_unidadesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_agregarDvd)
                                .addGap(18, 18, 18)
                                .addComponent(btn_modificarDvd)
                                .addGap(18, 18, 18)
                                .addComponent(btn_eliminarDvd)
                                .addGap(26, 26, 26)
                                .addComponent(btn_limpiarDvd)
                                .addGap(66, 66, 66)))
                        .addGap(51, 51, 51)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_categoria)
                        .addComponent(txt_idCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_idDvd)
                        .addComponent(txt_idDvd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_material)
                        .addComponent(txt_idMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Director)
                    .addComponent(lbl_Duracion)
                    .addComponent(lbl_genero)
                    .addComponent(txt_director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_unidadesdisponibles)
                    .addComponent(lbl_titulo)
                    .addComponent(lbl_codigo)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_unidadesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarDvd)
                    .addComponent(btn_modificarDvd)
                    .addComponent(btn_eliminarDvd)
                    .addComponent(btn_limpiarDvd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idDvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idDvdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idDvdActionPerformed

    private void txt_idMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idMaterialActionPerformed

    private void txt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tituloActionPerformed

    private void btn_agregarDvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarDvdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarDvdActionPerformed

    private void txt_idCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idCategoriaActionPerformed

      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_agregarDvd;
    public javax.swing.JButton btn_eliminarDvd;
    public javax.swing.JButton btn_limpiarDvd;
    public javax.swing.JButton btn_modificarDvd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Director;
    private javax.swing.JLabel lbl_Duracion;
    private javax.swing.JLabel lbl_categoria;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_genero;
    private javax.swing.JLabel lbl_idDvd;
    private javax.swing.JLabel lbl_material;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_unidadesdisponibles;
    public javax.swing.JSpinner sp_unidadesDisponibles;
    public javax.swing.JTable tabla_Dvd;
    public javax.swing.JTextField txt_codigo;
    public javax.swing.JTextField txt_director;
    public javax.swing.JTextField txt_duracion;
    public javax.swing.JTextField txt_genero;
    public javax.swing.JTextField txt_idCategoria;
    public javax.swing.JTextField txt_idDvd;
    public javax.swing.JTextField txt_idMaterial;
    public javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
