/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorLibros;
import Modelo.LibroDAO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Carlos Hernandez
 */
public class LibrosForm extends javax.swing.JFrame {

    LibroDAO LibroDAO = new LibroDAO();

    /**
     * Creates new form LibrosForm1
     */
    public LibrosForm() {
        initComponents();
        setLocationRelativeTo(null);

        ControladorLibros controladorLibros = new ControladorLibros(this, LibroDAO);
        btn_agregarLibros.addActionListener(controladorLibros);
        btn_modificarLibros.addActionListener(controladorLibros);
        btn_eliminarLibros.addActionListener(controladorLibros);
        btn_limpiarLibros.addActionListener(controladorLibros);
        tabla_Libros.setModel(LibroDAO.selectlibros());

        // METODO PARA CAPURAR LOS EVENTOS DEL MOUSE AL HACER CLICK
        this.tabla_Libros.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                obtenerDatosTabla(e);
                ModificarEliminarBtn();
            }
        });

        Limpiar();
        /*try {
            formatoFecha();
        } catch (ParseException ex) {

        } */
    }

    public void ModificarEliminarBtn() {

        txt_idLibros.setEnabled(false);
        txt_idMaterial.setEnabled(false);
        txt_idCategoria.setEnabled(false);

        btn_agregarLibros.setEnabled(false);
        btn_modificarLibros.setEnabled(true);
        btn_eliminarLibros.setEnabled(true);
    }

    public void Limpiar() {
        txt_idLibros.setEnabled(false);
        txt_idMaterial.setEnabled(false);
        txt_idCategoria.setEnabled(true);
        txt_idLibros.setText("");
        txt_idMaterial.setText("");
        txt_idCategoria.setText("");
        txt_autor.setText("");
        txt_Numero_de_pagina.setText("");
        txt_Editorial.setText("");
        txt_Isbn.setText("");
        txt_anio_publicacion.setText("");
        txt_codigo.setText("");
        txt_titulo.setText("");
        sp_unidadesDisponibles.setValue(0);

        btn_agregarLibros.setEnabled(true);
        btn_modificarLibros.setEnabled(false);
        btn_eliminarLibros.setEnabled(false);
    }

    private void obtenerDatosTabla(MouseEvent e) {

        int filaSeleccionada = tabla_Libros.getSelectedRow();

        if (filaSeleccionada > -1) {
            String id_libro = tabla_Libros.getValueAt(filaSeleccionada, 0).toString();
            String id_material = tabla_Libros.getValueAt(filaSeleccionada, 1).toString();
            String id_categoria = tabla_Libros.getValueAt(filaSeleccionada, 2).toString();
            String autor = tabla_Libros.getValueAt(filaSeleccionada, 3).toString();
            String Numero_de_pagina = tabla_Libros.getValueAt(filaSeleccionada, 4).toString();
            String editorial = tabla_Libros.getValueAt(filaSeleccionada, 5).toString();
            String Isbn = tabla_Libros.getValueAt(filaSeleccionada, 6).toString();
            String Año_publicacion = tabla_Libros.getValueAt(filaSeleccionada, 7).toString();
            String codigo = tabla_Libros.getValueAt(filaSeleccionada, 8).toString();
            String titulo = tabla_Libros.getValueAt(filaSeleccionada, 9).toString();
            String unidadesDisponibles = tabla_Libros.getValueAt(filaSeleccionada, 10).toString();

            txt_idLibros.setText(id_libro);
            txt_idMaterial.setText(id_material);
            txt_idCategoria.setText(id_categoria);
            txt_autor.setText(autor);
            txt_Numero_de_pagina.setText(Numero_de_pagina);
            txt_Editorial.setText(editorial);
            txt_Isbn.setText(Isbn);
            txt_anio_publicacion.setText(Año_publicacion);
            txt_codigo.setText(codigo);
            txt_titulo.setText(titulo);
            sp_unidadesDisponibles.setValue(Integer.parseInt(unidadesDisponibles));
        }

    }
/*
    private void formatoFecha() throws ParseException {

        MaskFormatter mascara = new MaskFormatter("##/##/####");
        mascara.setPlaceholderCharacter('_');
       txt_anio_publicacion.setFormatterFactory(new DefaultFormatterFactory(mascara));

    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_unidadesdisponibles = new javax.swing.JLabel();
        lbl_Numero_de_pagina = new javax.swing.JLabel();
        txt_idCategoria = new javax.swing.JTextField();
        lbl_Editorial = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_autor = new javax.swing.JTextField();
        sp_unidadesDisponibles = new javax.swing.JSpinner();
        txt_titulo = new javax.swing.JTextField();
        txt_Editorial = new javax.swing.JTextField();
        txt_Numero_de_pagina = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Libros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_Isbn = new javax.swing.JTextField();
        lbl_codigo = new javax.swing.JLabel();
        lbl_idLibros = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_agregarLibros = new javax.swing.JButton();
        lbl_titulo = new javax.swing.JLabel();
        btn_modificarLibros = new javax.swing.JButton();
        lbl_idmaterial = new javax.swing.JLabel();
        lbl_idcategoria = new javax.swing.JLabel();
        btn_eliminarLibros = new javax.swing.JButton();
        txt_idMaterial = new javax.swing.JTextField();
        txt_idLibros = new javax.swing.JTextField();
        btn_limpiarLibros = new javax.swing.JButton();
        lbl_autor = new javax.swing.JLabel();
        txt_anio_publicacion = new javax.swing.JFormattedTextField();

        lbl_unidadesdisponibles.setText("Unidades Disponibles:");

        lbl_Numero_de_pagina.setText("Numero de Pagina");

        txt_idCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idCategoriaActionPerformed(evt);
            }
        });

        lbl_Editorial.setText("Editorial");

        txt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tituloActionPerformed(evt);
            }
        });

        tabla_Libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_Libros);

        jLabel1.setText("Isbn");

        lbl_codigo.setText("Codigo:");

        lbl_idLibros.setText("ID:");

        jLabel2.setText("Año de publicacion");

        btn_agregarLibros.setText("Agregar");
        btn_agregarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarLibrosActionPerformed(evt);
            }
        });

        lbl_titulo.setText("Titulo:");

        btn_modificarLibros.setText("Modificar ");

        lbl_idmaterial.setText("ID Meterial");

        lbl_idcategoria.setText("ID Categoria");

        btn_eliminarLibros.setText("Eliminar");

        txt_idMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idMaterialActionPerformed(evt);
            }
        });

        txt_idLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idLibrosActionPerformed(evt);
            }
        });

        btn_limpiarLibros.setText("Limpiar");

        lbl_autor.setText("autor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lbl_idLibros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_idLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_idmaterial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_unidadesdisponibles)
                        .addGap(18, 18, 18)
                        .addComponent(sp_unidadesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt_idMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_idcategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_idCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_anio_publicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(btn_agregarLibros)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modificarLibros)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminarLibros)
                        .addGap(26, 26, 26)
                        .addComponent(btn_limpiarLibros))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_autor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_codigo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_Numero_de_pagina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Numero_de_pagina, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_Editorial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_idcategoria)
                        .addComponent(txt_idCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_idLibros)
                        .addComponent(txt_idLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_idmaterial)
                        .addComponent(txt_idMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_autor)
                    .addComponent(lbl_Numero_de_pagina)
                    .addComponent(lbl_Editorial)
                    .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Numero_de_pagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_anio_publicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_unidadesdisponibles)
                    .addComponent(lbl_titulo)
                    .addComponent(lbl_codigo)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_unidadesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarLibros)
                    .addComponent(btn_modificarLibros)
                    .addComponent(btn_eliminarLibros)
                    .addComponent(btn_limpiarLibros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idCategoriaActionPerformed

    private void txt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tituloActionPerformed

    private void btn_agregarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarLibrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarLibrosActionPerformed

    private void txt_idMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idMaterialActionPerformed

    private void txt_idLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idLibrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idLibrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_agregarLibros;
    public javax.swing.JButton btn_eliminarLibros;
    public javax.swing.JButton btn_limpiarLibros;
    public javax.swing.JButton btn_modificarLibros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Editorial;
    private javax.swing.JLabel lbl_Numero_de_pagina;
    private javax.swing.JLabel lbl_autor;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_idLibros;
    private javax.swing.JLabel lbl_idcategoria;
    private javax.swing.JLabel lbl_idmaterial;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_unidadesdisponibles;
    public javax.swing.JSpinner sp_unidadesDisponibles;
    public javax.swing.JTable tabla_Libros;
    public javax.swing.JTextField txt_Editorial;
    public javax.swing.JTextField txt_Isbn;
    public javax.swing.JTextField txt_Numero_de_pagina;
    public javax.swing.JFormattedTextField txt_anio_publicacion;
    public javax.swing.JTextField txt_autor;
    public javax.swing.JTextField txt_codigo;
    public javax.swing.JTextField txt_idCategoria;
    public javax.swing.JTextField txt_idLibros;
    public javax.swing.JTextField txt_idMaterial;
    public javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
