/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorUsuario;
import Modelo.Usuario;
import Modelo.UsuarioDAO;

/**
 *
 * @author JONATHAN G
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        menu_gestionar_material = new javax.swing.JMenu();
        menu_cd = new javax.swing.JMenuItem();
        menu_dvd = new javax.swing.JMenuItem();
        menu_libro = new javax.swing.JMenuItem();
        menu_revista = new javax.swing.JMenuItem();
        menu_material_prestamo = new javax.swing.JMenuItem();
        menu_material_devolucion = new javax.swing.JMenuItem();
        menu_usuarios = new javax.swing.JMenu();
        menu_usuario_gestionar = new javax.swing.JMenuItem();
        menu_opciones = new javax.swing.JMenu();
        menu_opciones_contraseña = new javax.swing.JMenuItem();
        menu_salir = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu3.setText("jMenu3");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        jMenu8.setText("jMenu8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu4.setText("Materiales");

        menu_gestionar_material.setText("Gestionar");

        menu_cd.setText("CDS");
        menu_gestionar_material.add(menu_cd);

        menu_dvd.setText("DVDS");
        menu_dvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_dvdActionPerformed(evt);
            }
        });
        menu_gestionar_material.add(menu_dvd);

        menu_libro.setText("LIBROS");
        menu_gestionar_material.add(menu_libro);

        menu_revista.setText("REVISTAS");
        menu_gestionar_material.add(menu_revista);

        jMenu4.add(menu_gestionar_material);

        menu_material_prestamo.setText("Prestamos");
        menu_material_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_material_prestamoActionPerformed(evt);
            }
        });
        jMenu4.add(menu_material_prestamo);

        menu_material_devolucion.setText("Devoluciones");
        menu_material_devolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_material_devolucionActionPerformed(evt);
            }
        });
        jMenu4.add(menu_material_devolucion);

        jMenuBar1.add(jMenu4);

        menu_usuarios.setText("Usuarios");

        menu_usuario_gestionar.setText("Gestionar");
        menu_usuarios.add(menu_usuario_gestionar);

        jMenuBar1.add(menu_usuarios);

        menu_opciones.setText("Opciones");

        menu_opciones_contraseña.setText("Cambiar contraseña");
        menu_opciones.add(menu_opciones_contraseña);

        jMenuBar1.add(menu_opciones);

        menu_salir.setText("Salir");
        jMenuBar1.add(menu_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_material_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_material_prestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_material_prestamoActionPerformed

    private void menu_material_devolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_material_devolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_material_devolucionActionPerformed

    private void menu_dvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_dvdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_dvdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        Usuario usuario = new Usuario();
//        UsuarioDAO usuarioDao = new UsuarioDAO();
//        UsuarioPanel panel = new UsuarioPanel();
//        Menu menu = new Menu();
//        ControladorUsuario controladorUsuario = new ControladorUsuario(usuario, usuarioDao, panel, menu);
//        menu.setVisible(true);
    
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    public javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    public javax.swing.JMenuItem menu_cd;
    public javax.swing.JMenuItem menu_dvd;
    public javax.swing.JMenu menu_gestionar_material;
    public javax.swing.JMenuItem menu_libro;
    public javax.swing.JMenuItem menu_material_devolucion;
    public javax.swing.JMenuItem menu_material_prestamo;
    public javax.swing.JMenu menu_opciones;
    private javax.swing.JMenuItem menu_opciones_contraseña;
    public javax.swing.JMenuItem menu_revista;
    public javax.swing.JMenu menu_salir;
    public javax.swing.JMenuItem menu_usuario_gestionar;
    public javax.swing.JMenu menu_usuarios;
    // End of variables declaration//GEN-END:variables
}
