/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorMenu;
import Controlador.ControladorUsuario;
import Modelo.Usuario;
import Modelo.UsuarioDAO;
import javax.swing.JPanel;

/**
 *
 * @author JONATHAN G
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */

    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        ControladorMenu controladorMenu = new ControladorMenu(); //SE INSTANCIA EL CONTROLADOR Y SE LE MANDA TODOS LOS ACTION
        menu_cd.addActionListener(controladorMenu);              // PARA MANEJAR LOS EVENTOS DESDE EL CONTROLADOR  
        menu_dvd.addActionListener(controladorMenu);
        menu_libro.addActionListener(controladorMenu);
        menu_revista.addActionListener(controladorMenu);
        menu_material_prestamo.addActionListener(controladorMenu);
        menu_material_devolucion.addActionListener(controladorMenu);
        menu_usuario_gestionar.addActionListener(controladorMenu);
        menu_opciones_contraseña.addActionListener(controladorMenu);
        menu_opciones_salir.addActionListener(controladorMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_contenedor_menu = new javax.swing.JPanel();
        menu_bar = new javax.swing.JMenuBar();
        menu_materiales = new javax.swing.JMenu();
        menu_gestionar_material = new javax.swing.JMenu();
        menu_cd = new javax.swing.JMenuItem();
        menu_dvd = new javax.swing.JMenuItem();
        menu_libro = new javax.swing.JMenuItem();
        menu_revista = new javax.swing.JMenuItem();
        menu_material_prestamo = new javax.swing.JMenuItem();
        menu_material_devolucion = new javax.swing.JMenuItem();
        menu_usuarios = new javax.swing.JMenu();
        menu_usuario_gestionar = new javax.swing.JMenuItem();
        menu_opciones = new javax.swing.JMenu();
        menu_opciones_contraseña = new javax.swing.JMenuItem();
        menu_opciones_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIBLIOTECAUDB");

        pnl_contenedor_menu.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout pnl_contenedor_menuLayout = new javax.swing.GroupLayout(pnl_contenedor_menu);
        pnl_contenedor_menu.setLayout(pnl_contenedor_menuLayout);
        pnl_contenedor_menuLayout.setHorizontalGroup(
            pnl_contenedor_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        pnl_contenedor_menuLayout.setVerticalGroup(
            pnl_contenedor_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        menu_bar.setBackground(new java.awt.Color(102, 102, 102));

        menu_materiales.setText("Materiales");

        menu_gestionar_material.setText("Gestionar");

        menu_cd.setText("CDS");
        menu_gestionar_material.add(menu_cd);

        menu_dvd.setText("DVDS");
        menu_dvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_dvdActionPerformed(evt);
            }
        });
        menu_gestionar_material.add(menu_dvd);

        menu_libro.setText("LIBROS");
        menu_gestionar_material.add(menu_libro);

        menu_revista.setText("REVISTAS");
        menu_gestionar_material.add(menu_revista);

        menu_materiales.add(menu_gestionar_material);

        menu_material_prestamo.setText("Prestamos");
        menu_material_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_material_prestamoActionPerformed(evt);
            }
        });
        menu_materiales.add(menu_material_prestamo);

        menu_material_devolucion.setText("Devoluciones");
        menu_material_devolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_material_devolucionActionPerformed(evt);
            }
        });
        menu_materiales.add(menu_material_devolucion);

        menu_bar.add(menu_materiales);

        menu_usuarios.setText("Usuarios");

        menu_usuario_gestionar.setText("Gestionar_Usuarios");
        menu_usuario_gestionar.setActionCommand("Gestionar_Usuarios");
        menu_usuarios.add(menu_usuario_gestionar);

        menu_bar.add(menu_usuarios);

        menu_opciones.setText("Opciones");

        menu_opciones_contraseña.setText("Cambiar contraseña");
        menu_opciones.add(menu_opciones_contraseña);

        menu_opciones_salir.setText("Salir");
        menu_opciones.add(menu_opciones_salir);

        menu_bar.add(menu_opciones);

        setJMenuBar(menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_contenedor_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_contenedor_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_material_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_material_prestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_material_prestamoActionPerformed

    private void menu_material_devolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_material_devolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_material_devolucionActionPerformed

    private void menu_dvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_dvdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_dvdActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menu_bar;
    public javax.swing.JMenuItem menu_cd;
    public javax.swing.JMenuItem menu_dvd;
    public javax.swing.JMenu menu_gestionar_material;
    public javax.swing.JMenuItem menu_libro;
    public javax.swing.JMenuItem menu_material_devolucion;
    public javax.swing.JMenuItem menu_material_prestamo;
    public javax.swing.JMenu menu_materiales;
    public javax.swing.JMenu menu_opciones;
    public javax.swing.JMenuItem menu_opciones_contraseña;
    public javax.swing.JMenuItem menu_opciones_salir;
    public javax.swing.JMenuItem menu_revista;
    public javax.swing.JMenuItem menu_usuario_gestionar;
    public javax.swing.JMenu menu_usuarios;
    public javax.swing.JPanel pnl_contenedor_menu;
    // End of variables declaration//GEN-END:variables
}
